title: Shaopeng Sun's Homepage
page-top-title: Shaopeng Sun
top-section-bg-text: Digestive Diseases
home-subtitle: Shaopeng Sun&ensp;|&ensp;孙少鹏
copyright-text: '&copy; Shaopeng Sun 2024-2025. All Rights Reserved.'
