title: Shaopeng Sun's(孙少鹏) Homepage
page-top-title: Shaopeng Sun
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;孙少鹏
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
